sudo: false
os:
  - linux
  - windows
  - osx

cache: yarn

language: node_js
node_js:
  - "node"
  - "lts/*"
  - "14"
  - "12"
  - "10"

install: yarn install --immutable

script:
  - yarn build
  # - yarn lint
  - yarn test

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && coveralls < coverage/lcov.info
